# Generated by Django 3.2.15 on 2023-04-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorsPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='price_amount',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
