# Generated by Django 3.2.15 on 2022-10-10 14:19

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/', validators=[store.validators.validate_file_extension]),
        ),
    ]
