# Generated by Django 3.2.15 on 2022-11-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_merchant_id_order_payment_intent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
    ]
