# Generated by Django 3.2.15 on 2023-01-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='times_redeemed',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
