# Generated by Django 3.2.15 on 2023-01-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20230108_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipped_orders',
            name='delivery_company',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shipped_orders',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
