# Generated by Django 3.2.15 on 2023-01-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_stripe',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
