# Generated by Django 3.2.15 on 2023-03-06 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_carouselimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipped_Orders',
        ),
    ]
