# Generated by Django 3.2.15 on 2023-03-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_delete_shipped_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id', '-created_at')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user'], name='store_produ_user_id_a3f9ca_idx'),
        ),
    ]
