# Generated by Django 3.2.15 on 2022-11-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_inventory',
            name='discount',
        ),
    ]
