# Generated by Django 3.2.15 on 2023-03-27 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminStore', '0002_alter_conversation_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at',)},
        ),
    ]
