# Generated by Django 3.2.15 on 2023-03-06 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0029_delete_shipped_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipped_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=255)),
                ('tracking_number', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_company', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipped_orders', to='store.order')),
            ],
        ),
    ]
