# Generated by Django 3.2.15 on 2023-03-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipped_orders',
            options={'ordering': ('id',)},
        ),
    ]
